# Programming Assignment - 2
---
## Name: Samruth Vennapusala
---

## Question 1
---
Modify the textual data example from class to convert the document-term matrix into TF-IDF (term-frequency inverse document frequency) matrix by using basic NumPy operations where

>- Term-frequency (of a word in a document) is frequency of the word in a document divided by total number of words in the document.

>- Inverse document frequency of a word (all documents under consideration) is the natural log of (total number of documents/number of documents having the given word).

>- tf-idf(t, d) = tf(t,d)*idf(t) ; 

**Display the dense output for the tf-idf matrix for the example taken in class.**

In [48]:
# Your code comes here

## Example Documents: Amazon review of Taco vs Burrito
document1 = " I bought this game as a gift for my 8 year old daughter who loves games. I was expecting lots of gross foods--but I was surprised at the inappropriate cards--eyeball, human burger, blood salsa, and fresh brains. Those are not foods that typical people find in their refrigerators. We do not practice cannibalism. She was very upset when I suggested that we just take out those cards. I seriously wonder who thinks that those cards are appropriate for kids. The rest of the game is funny, but I wish I would have looked through the cards before I gave it to her."
document2 = "Absolutely love Taco vs burrito. I️ bought it as a kickstarter. I️ originally bought this game because my husband and I️ love to play games with friends but most of them are not targeted to children so I️ got this to add to our collection so we had options when our friends with kids came. I’m not gonna lie I️ did No have high expectations for this to be a game for adult but I️ was Sooooo wrong!!!!!! We have now played with several different groups of friends and it’s a hit!!!!! With adults it becomes a major strategy game. I️ have Now bought it as a Christmas present bc it was so well received!!!!"
document3 = " Unlike several of the reviewers here, I didn't purchase this originally for when kids are around. I bought it because of the reviews that said the adults all loved it too! I'm always on the lookout for games playable by 2 people and this was a great one. It's incredibly simple, but brings a lot of laughs with the competition and sabotage. I'm really glad I gave this game a chance."


## Create a bag of words

## Create a TF-IDF matrix

In [69]:
import re
import numpy as np
#getting rid of punction in code
document1 = re.sub(r'[^\w\s]', '', document1)
document2 = re.sub(r'[^\w\s]', '', document2)
document3 = re.sub(r'[^\w\s]', '', document3)

doc_list = [document1, document2, document3]

# Function

In [62]:
def tf(word, document):
    doclist = document.split()
    
    
    rawcount = document.count(word)
    totalamount = (len(doclist))
    tf = rawcount/totalamount
    print(tf)
    
    WordInDoc = 0 
    for i in range(len(doc_list)):
        doc = doc_list[i].split()
        rawcount = doc_list[i].count(word)
        if rawcount > 0:
            WordInDoc = WordInDoc + 1
    idf = len(doc_list)/WordInDoc
    print(idf)
    
    tf_idf = tf*idf
    return(tf_idf)
    



## Creating Bag of Words

In [79]:
tot_doc = document1 + " " + document2 + " " + document3
uniqueWords = list(set(tot_doc.split()))
print(uniqueWords)

['foods', '2', 'before', 'gonna', 'just', 'We', 'came', 'so', 'strategy', 'play', 'vs', 'received', 'gave', 'game', 'appropriate', 'find', 'gross', 'I', 'here', 'major', '8', 'husband', 'Im', 'are', 'in', 'games', 'Sooooo', 'competition', 'originally', 'human', 'refrigerators', 'not', 'now', 'this', 'as', 'wonder', 'but', 'funny', 'bc', 'the', 'several', 'options', 'With', 'purchase', 'groups', 'blood', 'great', 'friends', 'those', 'its', 'cards', 'love', 'when', 'had', 'her', 'through', 'wrong', 'surprised', 'got', 'targeted', 'Christmas', 'lot', 'be', 'adults', 'high', 'old', 'fresh', 'most', 'inappropriate', 'my', 'we', 'for', 'of', 'did', 'around', 'hit', 'didnt', 'Taco', 'suggested', 'kids', 'cannibalism', 'played', 'glad', 'brains', 'burger', 'brings', 'year', 'thinks', 'one', 'people', 'collection', 'lie', 'our', 'because', 'said', 'foodsbut', 'to', 'well', 'upset', 'Now', 'burrito', 'a', 'who', 'No', 'Those', 'practice', 'laughs', 'out', 'children', 'wish', 'have', 'with', 'rea

## Running through function

In [91]:

OutputMatrix = np.zeros((163,3))
for l in range(len(uniqueWords)):
    for k in range(len(doc_list)):
        OutputMatrix[l,k] = tf(uniqueWords[l],doc_list[k])


0.0196078431372549
3.0
0.0
3.0
0.0
3.0
0.0
3.0
0.0
3.0
0.014084507042253521
3.0
0.00980392156862745
3.0
0.0
3.0
0.0
3.0
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.00980392156862745
3.0
0.0
3.0
0.0
3.0
0.00980392156862745
1.5
0.008695652173913044
1.5
0.0
1.5
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.0
3.0
0.034782608695652174
3.0
0.0
3.0
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.0
1.5
0.017391304347826087
1.5
0.014084507042253521
1.5
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.00980392156862745
1.5
0.0
1.5
0.014084507042253521
1.5
0.029411764705882353
1.0
0.034782608695652174
1.0
0.028169014084507043
1.0
0.0196078431372549
3.0
0.0
3.0
0.0
3.0
0.00980392156862745
3.0
0.0
3.0
0.0
3.0
0.00980392156862745
3.0
0.0
3.0
0.0
3.0
0.0784313725490196
1.0
0.06956521739130435
1.0
0.08450704225352113
1.0
0.0
3.0
0.0
3.0
0.014084507042253521
3.0
0.0
3.0
0.008695652173913044
3.0
0.0
3.0
0.00980392156862745
3.0
0.0
3.0
0.0
3.0
0.0
3.0
0.008695652173913044
3.0
0.

In [92]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

<IPython.core.display.Javascript object>

## Output matrix for tf-idf. Word vs Document

In [93]:

print(OutputMatrix)

[[0.05882353 0.         0.        ]
 [0.         0.         0.04225352]
 [0.02941176 0.         0.        ]
 [0.         0.02608696 0.        ]
 [0.02941176 0.         0.        ]
 [0.01470588 0.01304348 0.        ]
 [0.         0.02608696 0.        ]
 [0.         0.10434783 0.        ]
 [0.         0.02608696 0.        ]
 [0.         0.02608696 0.02112676]
 [0.         0.02608696 0.        ]
 [0.         0.02608696 0.        ]
 [0.01470588 0.         0.02112676]
 [0.02941176 0.03478261 0.02816901]
 [0.05882353 0.         0.        ]
 [0.02941176 0.         0.        ]
 [0.02941176 0.         0.        ]
 [0.07843137 0.06956522 0.08450704]
 [0.         0.         0.04225352]
 [0.         0.02608696 0.        ]
 [0.02941176 0.         0.        ]
 [0.         0.02608696 0.        ]
 [0.         0.01304348 0.04225352]
 [0.01960784 0.00869565 0.01408451]
 [0.05882353 0.00869565 0.04225352]
 [0.00980392 0.00869565 0.01408451]
 [0.         0.02608696 0.        ]
 [0.         0.         0.04